# Generated by Django 3.2.1 on 2021-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayers',
            name='first_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nbaplayers',
            name='height_inches',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nbaplayers',
            name='height_meters',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nbaplayers',
            name='last_name',
            field=models.CharField(default='null', max_length=120),
            preserve_default=False,
        ),
    ]
