# Generated by Django 3.2.1 on 2021-05-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210505_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbaplayers',
            old_name='height_inches',
            new_name='h_inches',
        ),
        migrations.RenameField(
            model_name='nbaplayers',
            old_name='height_meters',
            new_name='h_meters',
        ),
    ]
