# Generated by Django 3.2.1 on 2021-05-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210505_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbaplayers',
            old_name='h_inches',
            new_name='h_in',
        ),
    ]
